System hostname = b43bsd-test
Which network interface = em0
IPv4 address for em0 = dhcp
IPv6 address for em0 = none
Password for root = test
Which disk = sd0
Use (W)hole disk = yes
Location of sets = http
HTTP proxy = none
HTTP Server = cdn.openbsd.org
Server directory = pub/OpenBSD/7.9/amd64
Set name(s) = -all
Set name(s) = bsd
Set name(s) = bsd.rd
Set name(s) = base79
Set name(s) = comp79
Set name(s) = man79
Set name(s) = done
What timezone are you in = UTC
Start sshd(8) by default = yes
Allow root ssh login = yes
Setup a user = no
Do you expect to run the X Window System = no
