System hostname = b43bsd-test
Which network interface = re0
IPv4 address for re0 = dhcp
IPv6 address for re0 = none
Password for root = test
Which disk = sd0
Use (W)hole disk = yes
location of sets = http
HTTP Server = cdn.openbsd.org
Set = -all
Set = bsd
Set = bsd.rd
Set = base71
Set = comp71
Set = man71
Directory = pub/OpenBSD/7.9/amd64
